
aws:
  region: us-east-1
  endpoint: ${AWS_ENDPOINT:#{null}}
  kms:
    keyId: ${PAGINATION_KEY_ID:00000000-0000-0000-0000-000000000001}

spring:
  main:
    allow-bean-definition-overriding: true


