cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access_key: ASIAY7BDJFZNAOHRWXUY
      secret_key: /jrOmx9Sf3TzcBj3FVk1boN5Xt5DXjUQvRWLj698
    end_point:
      uri: https://sqs.us-east-1.amazonaws.com/816867951976/MessaginQueue.fifo
# mongodb+srv://fm1539:fMDhvPfP922X8rXN@traversecluster.fk3mwfb.mongodb.net/?retryWrites=true&w=majority

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${MONGO_URL}
